auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from forms import LoginForm, RegistrationForm
from models import session, Users
from flask import request, Response, render_template, url_for, flash, redirect
import sqlalchemy

engine = sqlalchemy.create_engine(
    "postgresql://postgres:postgres@localhost/postgres"
)
db = engine.connect()

auth = Blueprint('auth', __name__)

@auth.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = session.query(Users).filter_by(email=f'{form.email.data}',password=f'{form.password.data}').first()
            #statement = sqlalchemy.text(f"SELECT * FROM users WHERE email='{form.email.data}' AND password='{form.password.data}';")
            #guest = session.execute(statement).first()
            if user:
                flash(f'Login Successful for {form.email.data}', 'success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Login Unsuccessful. Please check email and password', 'danger')
                return redirect(url_for('auth.login'))
            
    return render_template('login.html', title='Login', form=form, user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route("/register", methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    user = None
    if request.method == 'POST':
        if form.validate_on_submit():
            #user = session.query(Users).filter_by(email=f'{form.email.data}',password=f'{form.password.data}').first()
            statement = sqlalchemy.text(f"SELECT * FROM users WHERE email='{form.email.data}' AND password='{form.password.data}';")
            user = session.execute(statement).first()
            if user:
                flash('Email already exists.', category='error')
                return redirect(url_for('auth.register'))
            
            else:
                try:
                    statement = sqlalchemy.text(f"INSERT INTO users VALUES ('{form.username.data}', '{form.email.data}', '{form.password.data}');")            
                    db.execute(statement)
                    db.commit()
                    
                    user = session.query(Users).filter_by(email=f'{form.email.data}',password=f'{form.password.data}').first()
                    #statement = sqlalchemy.text(f"SELECT * FROM users WHERE email='{form.email.data}' AND password='{form.password.data}';")
                    #user = session.execute(statement).first()
                    login_user(user, remember=True)
                    flash(f'Account created for {form.username.data}!', 'success')
                    return redirect(url_for('views.home'))
                except Exception as e:
                    db.rollback()
                    return Response(str(e), 403)
        
    return render_template('register.html', title='Register', form=form, user=current_user)

views.py
from flask import request, Response, render_template, Blueprint, flash, url_for, redirect
from flask_login import login_required, current_user
import sqlalchemy
import json
from models import db
from decimal import Decimal
from typing import Dict
from forms import UpdateAccountForm, BookingForm, FilterForm, UpdatePropertiesForm, StatsForm
from datetime import datetime

posts = [
    {
        'author': 'ADMINS',
        'title': 'WELCOME',
        'content': 'Properties are available under Listings',
        'date_posted': 'March 24, 2023'
    }
]

views = Blueprint('views', __name__)

@views.route("/")
@views.route("/home")
@login_required
def home():
    return render_template('home.html', posts=posts, user=current_user)

@views.route("/")
@views.route("/listings", methods=["GET", "POST"])
@login_required
def get_relation():
    try:
        form = FilterForm()
        statement = sqlalchemy.text(f"SELECT * FROM PROPERTIES;")
        res = db.execute(statement)
        data = generate_table_return_result(res)
        data = json.loads(data)

        if form.validate_on_submit():
            property_type = form.property_type.data
            min_price = form.min_price.data
            max_price = form.max_price.data
            neighbourhood = form.neighbourhood.data
            except_neighbourhood = form.except_neighbourhood.data
            price_sort_by = form.price_sort_by.data
            bookings_sort_by = form.bookings_sort_by.data
            
            statement = "SELECT p.* FROM properties p, bookings b WHERE b.property_id = p.property_id AND b.owner_email = p.owner"
            if property_type:
                if (property_type == 'Others'):
                    statement += f" AND p.property_type NOT IN ('House', 'Apartment', 'Condominium')"
                elif (property_type != 'None'):
                    statement += f" AND p.property_type ='{property_type}'"
            if min_price:
                statement += f" AND p.price_per_night >= {min_price}"
            if max_price:
                statement += f" AND p.price_per_night <= {max_price}"
            if neighbourhood:
                if (neighbourhood != 'All'):
                    statement += f" AND p.neighbourhood ='{neighbourhood}'"
            if except_neighbourhood:
                if (except_neighbourhood != 'None'):
                    statement += f" AND p.neighbourhood !='{except_neighbourhood}'"
            if bookings_sort_by:
                statement += f" GROUP BY p.property_id ORDER BY COUNT(*) {bookings_sort_by}"
            if price_sort_by:
                statement += f" , price_per_night {price_sort_by}" 
    
            statement = sqlalchemy.text(statement)
            listings = db.execute(statement)
            listings = generate_table_return_result(listings)
            listings = json.loads(listings)
            return render_template('listings.html', title='Listings', form=form, table_data=listings, user=current_user)
        return render_template('listings.html', title='Listings', form=form, table_data=data, user=current_user)

    except Exception as e:
        db.rollback()
        return Response(str(e), 403)

@views.route("/")
@views.route("/mylistings", methods=["GET", "POST"])
@login_required
def get_my_listings():
    try:
        statement = sqlalchemy.text(f"SELECT * FROM properties where owner = '{current_user.email}';")
        res = db.execute(statement)
        data = generate_table_return_result(res)
        data = json.loads(data)
        return render_template('myownlistings.html', title='My Listings', table_data=data, user=current_user)

    except Exception as e:
        db.rollback()
        return Response(str(e), 403)

@views.route('/updatemylistings', methods=['GET', 'POST'])
@login_required
def update_listings():
    form = UpdatePropertiesForm()

    if request.method == 'POST' and form.validate_on_submit():
        try:
            statement = sqlalchemy.text(f"UPDATE properties SET price_per_night = '{form.price_per_night.data}', accomodates  = '{form.accommodates.data}',  amenities = '{form.amenities.data}' WHERE property_id = '{form.property_id.data}';")
            db.execute(statement)
            db.commit()
            flash('Your listing has been updated!', 'success')
            return redirect(url_for('views.get_my_listings'))
        except Exception as e:
            db.rollback()
            return Response(str(e), 403)
    property_id = request.args.get('property_id')
    form.property_id.data = property_id
    statement = sqlalchemy.text(f"SELECT * FROM properties WHERE property_id = {property_id}")
    res = db.execute(statement)
    data = json.loads(generate_table_return_result(res))
    form.price_per_night.data = data['rows'][0]['price_per_night']
    form.accommodates.data = data['rows'][0]['accomodates']
    form.amenities.data = data['rows'][0]['amenities']
    return render_template('updatemylistings.html', title='Update Listings', form=form, user=current_user)  

@views.route('/delete_entry', methods=['POST'])
def delete_entry():
    id = request.args.get('id')
    statement = sqlalchemy.text(f"DELETE FROM properties WHERE property_id = {id};")
    db.execute(statement)
    db.commit()
    flash('Property deleted successfully!', 'success')
    return redirect(url_for('views.get_my_listings'))

@views.route('/booking', methods=['GET', 'POST'])
@login_required
def booking():
    form = BookingForm()
    property_id = request.args.get('property_id')
    form.property_id.data = property_id
    statement = sqlalchemy.text(f"SELECT owner FROM PROPERTIES WHERE property_id = '{form.property_id.data}' ;")
    res = db.execute(statement)
    data = json.loads(generate_table_return_result(res))
    form.owner_email.data = data['rows'][0]['owner']
    if form.validate_on_submit():
        try:
            statement = sqlalchemy.text(f"SELECT * FROM users u WHERE u.email='{form.guest_email.data}';")
            guest = db.execute(statement)
            db.commit()
        except Exception as e:
            db.rollback()
            flash(str(e), 'error')     
        try:
            start_date= form.start_date.data
            end_date = form.end_date.data
            # Check that the start date is not earlier than today's date
            if start_date < datetime.now().date():
                flash('Start date cannot be earlier than today.', category='error')
                return redirect(f"/booking?property_id={form.property_id.data}")
            
            # Check that the end date is not earlier than the start date
            if end_date < start_date:
                flash('End date cannot be earlier than start date.', category='error')
                return redirect(f"/booking?property_id={form.property_id.data}")
            
            # Check that booking dates do not overlap with existing bookings
            statement = sqlalchemy.text(f"SELECT * FROM bookings WHERE property_id ='{form.property_id.data}' AND (('{form.start_date.data}' BETWEEN start_date AND end_date) OR ('{form.end_date.data}' BETWEEN start_date AND end_date));")
            conflict_booking = db.execute(statement).fetchall()
            if conflict_booking:
                flash('Booking dates conflict with another booking on this property.', category='error')
                return redirect(f"/booking?property_id={form.property_id.data}")
            duration = end_date - start_date
            days = duration.days
        except Exception as e:
            db.rollback()
            flash(str(e), 'error')  
        try:
            statement = sqlalchemy.text(f"INSERT INTO bookings VALUES ('{form.guest_email.data}', '{form.owner_email.data}', '{form.property_id.data}', '{form.start_date.data}',  '{form.end_date.data}', {days});")
            db.execute(statement)
            db.commit()
            flash('Your booking has been confirmed!', 'success')
            return redirect(f"/booking?property_id={form.property_id.data}")
        except sqlalchemy.exc.SQLAlchemyError as e:
            db.rollback()
            flash('Your email must match your account email.', category='error')
            return redirect(f"/booking?property_id={form.property_id.data}")
    return render_template('booking.html', title='Booking', form = form, user=current_user)


@views.route("/profile", methods=['GET', 'POST'])
@login_required
def profile():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.email.data != current_user.email:
            statement = sqlalchemy.text(f"SELECT * FROM users u WHERE u.email='{form.email.data}';")
            guest = db.execute(statement).fetchone()
            db.commit()
            if guest:
                flash('That email is taken. Please choose a different one.', category='error')
                return redirect(url_for('views.profile'))
        if form.name.data != current_user.name:
            statement = sqlalchemy.text(f"SELECT * FROM users u WHERE u.name='{form.name.data}';")
            guest = db.execute(statement).fetchone()
            db.commit()
            if guest:
                flash('That name is taken. Please choose a different one.', category='error')
                return redirect(url_for('views.profile'))    
        # if both new name and email are valid
        try:
            statement = sqlalchemy.text(f"UPDATE users SET email = '{form.email.data}', name = '{form.name.data}' WHERE email = '{current_user.email}';")       
            db.execute(statement)
            db.commit()

            statement = sqlalchemy.text(f"SELECT * FROM users g WHERE g.name='{form.name.data}' AND g.email='{form.email.data}';")
            guest = db.execute(statement)
            db.commit()
            guest = generate_table_return_result(guest)
            guest = json.loads(guest)

            flash('Your account has been updated! Please log in again.', 'success')

templates/booking.html
{% extends "layout.html" %} {% block content %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Book Accommodation</legend>
      <div class="form-group">
        {{ form.guest_email.label(class="form-control-label") }} {% if
        form.guest_email.errors %} {{ form.guest_email(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.guest_email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.guest_email(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.owner_email.label(class="form-control-label") }} {% if
        form.owner_email.errors %} {{ form.owner_email(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.owner_email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.owner_email(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.property_id.label(class="form-control-label") }} {% if
        form.property_id.errors %} {{ form.property_id(class="form-control
        form-control-lg is-invalid", readonly="readonly") }}
        <div class="invalid-feedback">
          {% for error in form.property_id.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.property_id(class="form-control form-control-lg",
        readonly="readonly") }} {% endif %}
      </div>
      <div class="form-group">
        {{ form.start_date.label(class="form-control-label") }} {% if
        form.start_date.errors %} {{ form.start_date(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.start_date.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.start_date(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.end_date.label(class="form-control-label") }} {% if
        form.end_date.errors %} {{ form.end_date(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.end_date.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.end_date(class="form-control form-control-lg") }} {%
        endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}

templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    <div class="border-top pt-3">
      <small class="text-muted">
          <a class="ml-2" href="{{ url_for('admin.index') }}"> Access Admin Interface </a>
      </small>
  </div>
{% endblock content %}

templates/index.html
{% extends 'admin/master.html' %}
{% block body %}
    Hello World from MyView!
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>SQLodge - {{ title }}</title>
    {% else %}
        <title>SQLodge</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">SQLodge</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            {% if user.is_authenticated %}
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('views.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('views.get_relation') }}">Listings</a>
              <a class="nav-item nav-link" href="{{ url_for('views.profile') }}">Profile</a>
              <a class="nav-item nav-link" href="{{ url_for('views.get_my_listings') }}">My Listings</a>
              <a class="nav-item nav-link" href="{{ url_for('views.statistics') }}">My Statistics</a>
              <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
            </div>
            {% else %}
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a>
            </div>
            {% endif%}
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/listings.html
{% extends "layout.html" %} {% block content %}
<style>
  table {
    font-family: Arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }

  th,
  td {
    border: 1px solid #ddd;
    padding: 8px;
  }

  th {
    text-align: left;
    background-color: #f2f2f2;
  }

  tr:nth-child(even) {
    background-color: #f2f2f2;
  }

  .btn-book {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 8px 16px;
    border-radius: 4px;
  }

  .btn-book:hover {
    background-color: #0062cc;
  }

  h1 {
    font-size: 26px;
  }
</style>
<div class="container">
  <h1>Fill in all fields to use filter function!</h1>
  <form method="POST" action="{{ url_for('views.get_relation') }}">
    {{ form.csrf_token }}
    <div class="form-group">
      <label>{{ form.property_type.label }}</label>
      {{ form.property_type }}
    </div>
    <div class="form-group">
      <label>{{ form.min_price.label }}</label>
      {{ form.min_price }}
    </div>
    <div class="form-group">
      <label>{{ form.max_price.label }}</label>
      {{ form.max_price }}
    </div>
    <div class="form-group">
      <label>Neighbourhood</label>
      {{ form.neighbourhood }}
      <span> Except </span>
      {{ form.except_neighbourhood }}
    </div>
    <div class="form-group">
      <label>{{ form.price_sort_by.label }}</label>
      {{ form.price_sort_by }}
    </div>
    <div class="form-group">
      <label>{{ form.bookings_sort_by.label }}</label>
      {{ form.bookings_sort_by }}
    </div>
    <div class="form-group">{{ form.submit }}</div>
  </form>
  <h1>Click Property ID to book</h1>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Owner</th>
        <th>Name</th>
        <th>Type</th>
        <th>Price Per Night</th>
        <th>Location</th>
        <th>Size</th>
        <th>Accommodates</th>
        <th>Amenities</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for row in table_data['rows'] %}
      <tr>
        <td>
          <a href="/booking?property_id={{ row['property_id'] }}"
            >{{ row['property_id'] }}</a
          >
        </td>
        <td>{{ row['owner'] }}</td>
        <td>{{ row['property_name'] }}</td>
        <td>{{ row['property_type'] }}</td>
        <td>{{ row['price_per_night'] }}</td>
        <td>
          {{ row['city'] }}, {{ row['neighbourhood'] }}, {{ row['zipcode'] }}
        </td>
        <td>{{ row['square_feet'] }}</td>
        <td>{{ row['accomodates'] }}</td>
        <td>{{ row['amenities'] }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

templates/login.html
{% extends "layout.html" %} {% block content %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Log In</legend>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }} {% if
        form.email.errors %} {{ form.email(class="form-control form-control-lg
        is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.email(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }} {% if
        form.password.errors %} {{ form.password(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.password(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <!-- <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon">Sign in as: </span>
                            <SELECT type="user_select" class="selectpicker form-control">
                                <option value="guest">guest</option>
                                <option value="owner">owner</option>
                                <option value="admin">admin</option>
                            </SELECT>
                    </div>
                </div> -->
      <div class="form-check">
        {{ form.remember(class="form-check-input") }} {{
        form.remember.label(class="form-check-label") }}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
    <small class="text-muted ml-2">
      <a href="#">Forgot Password?</a>
    </small>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted">
    Need An Account?
    <a class="ml-2" href="{{ url_for('auth.register') }}">Sign Up Now</a>
  </small>
</div>
{% endblock content %}

templates/myownlistings.html
{% extends "layout.html" %} {% block content %}
<style>
  table {
    font-family: Arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }

  th,
  td {
    border: 1px solid #ddd;
    padding: 8px;
  }

  th {
    text-align: left;
    background-color: #f2f2f2;
  }

  tr:nth-child(even) {
    background-color: #f2f2f2;
  }

  .btn-book {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 8px 16px;
    border-radius: 4px;
  }

  .btn-book:hover {
    background-color: #0062cc;
  }

  h1 {
    font-size: 28px;
  }
</style>
<div class="container">
  <h1>Click Property ID to update</h1>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Owner</th>
        <th>Name</th>
        <th>Type</th>
        <th>Price per Night</th>
        <th>Location</th>
        <th>Size</th>
        <th>Accommodates</th>
        <th>Amenities</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for row in table_data['rows'] %}
      <tr>
        <td>
          <a href="/updatemylistings?property_id={{ row['property_id'] }}"
            >{{ row['property_id'] }}</a
          >
        </td>
        <td>{{ row['owner'] }}</td>
        <td>{{ row['property_name'] }}</td>
        <td>{{ row['property_type'] }}</td>
        <td>{{ row['price_per_night'] }}</td>
        <td>
          {{ row['city'] }}, {{ row['neighbourhood'] }}, {{ row['zipcode'] }}
        </td>
        <td>{{ row['square_feet'] }}</td>
        <td>{{ row['accomodates'] }}</td>
        <td>{{ row['amenities'] }}</td>
        <td>
          <form
            method="post"
            action="{{ url_for('views.delete_entry', id=row['property_id']) }}"
            onsubmit="return confirm('Are you sure you want to delete this listing?');"
          >
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

templates/profile.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.name }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Update Account</legend>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}

                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}